# -*- coding: utf-8 -*-

from PyQt5.QtWidgets import QApplication, QMainWindow, QTableWidgetItem, QTableWidget
import sys

from db.search_op import search_surgery_info
from intermediate_data_structure.search_info import SearchInfo
from intermediate_data_structure.surgery_info import SurgeryInfo
from ui.print_dialog import PrintDialog  # 导入打印窗口类（假设文件名为 print_dialog.py）

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '查询条件2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(380, 20, 320, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)

        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 80, 704, 210))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout.addWidget(self.lineEdit_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout.addWidget(self.lineEdit_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_6.addWidget(self.label_21)
        self.dateTimeEdit_6 = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit_6.setObjectName("dateTimeEdit_6")
        self.horizontalLayout_6.addWidget(self.dateTimeEdit_6)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_6.addWidget(self.label_22)
        self.dateTimeEdit_4 = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit_4.setObjectName("dateTimeEdit_4")
        self.horizontalLayout_6.addWidget(self.dateTimeEdit_4)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_6.addWidget(self.label_23)
        self.dateTimeEdit_5 = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit_5.setObjectName("dateTimeEdit_5")
        self.horizontalLayout_6.addWidget(self.dateTimeEdit_5)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.dateTimeEdit_3 = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit_3.setObjectName("dateTimeEdit_3")
        self.horizontalLayout_6.addWidget(self.dateTimeEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_7.addWidget(self.label_29)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_7.addWidget(self.lineEdit_20)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_7.addWidget(self.label_27)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_7.addWidget(self.lineEdit_19)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_7.addWidget(self.label_25)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_7.addWidget(self.lineEdit_21)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_7.addWidget(self.label_32)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_7.addWidget(self.lineEdit_24)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_8.addWidget(self.label_31)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_8.addWidget(self.lineEdit_23)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_8.addWidget(self.label_30)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_8.addWidget(self.dateEdit)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_8.addWidget(self.label_24)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_8.addWidget(self.dateEdit_2)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_8.addWidget(self.label_28)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.horizontalLayout_8.addWidget(self.lineEdit_22)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 350, 700, 200))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setHorizontalHeaderLabels([
            "病历号", "患者姓名", "性别", "手术日期", "手术名称", "医生名称"

        ])

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        self.pushButton_4.clicked.connect(MainWindow.close)  # 关闭按钮点击关闭主窗口
        self.pushButton_2.clicked.connect(self.openPrintDialog)  # 打印按钮连接打印窗口
        self.pushButton.clicked.connect(self.openQueryDialog)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "手术信息查询"))
        self.pushButton.setText(_translate("MainWindow", "查询(&S)"))
        self.pushButton_2.setText(_translate("MainWindow", "打印(&P)"))
        self.pushButton_3.setText(_translate("MainWindow", "导出(&D)"))
        self.pushButton_4.setText(_translate("MainWindow", "退出(&E)"))
        self.label.setText(_translate("MainWindow", "病历号;"))
        self.label_4.setText(_translate("MainWindow", "患者姓名："))
        self.label_5.setText(_translate("MainWindow", "性别："))
        self.label_6.setText(_translate("MainWindow", "医疗付款方式："))
        self.comboBox.setItemText(0, _translate("MainWindow", "微信"))
        self.comboBox.setItemText(1, _translate("MainWindow", "支付宝"))
        self.comboBox.setItemText(2, _translate("MainWindow", "现金"))
        self.comboBox.setItemText(3, _translate("MainWindow", "其他"))
        self.label_21.setText(_translate("MainWindow", "入院时间："))
        self.label_22.setText(_translate("MainWindow", "——"))
        self.label_23.setText(_translate("MainWindow", "出院时间："))
        self.label_20.setText(_translate("MainWindow", "——"))
        self.label_29.setText(_translate("MainWindow", "科室："))
        self.label_27.setText(_translate("MainWindow", "住院天数："))
        self.label_25.setText(_translate("MainWindow", "——"))
        self.label_32.setText(_translate("MainWindow", "年龄："))
        self.label_31.setText(_translate("MainWindow", "手术名称："))
        self.label_30.setText(_translate("MainWindow", "手术日期："))
        self.label_24.setText(_translate("MainWindow", "——"))
        self.label_28.setText(_translate("MainWindow", "医生姓名："))
        '''self.lineEdit.setText("1")
        self.lineEdit_4.setText("4")
        self.lineEdit_5.setText("5")
        self.lineEdit_20.setText("20")
        self.lineEdit_19.setText("19")
        self.lineEdit_4.setText("4")
        self.lineEdit_17.setText("17")
        self.lineEdit_18.setText("18")'''


    def openPrintDialog(self):
        """打开打印窗口"""
        self.printDialog = PrintDialog()  # 创建打印窗口实例
        self.printDialog.show()  # 显示打印窗口

    def openQueryDialog(self):

        index = self.comboBox.currentIndex()
        payment = self.comboBox.itemText(index)

        search_info = {
            "medical_record_number": self.lineEdit.text(),
            "patient_name": self.lineEdit_4.text(),
            "patient_gender": self.lineEdit_5.text(),
            "payment_method": payment,
            "admission_date_from": self.dateTimeEdit_6.dateTime().toString('yyyy-MM-dd'),  # 入院时间开始
            "admission_date_to": self.dateTimeEdit_4.dateTime().toString('yyyy-MM-dd'),  # 入院时间结束
            "discharge_date_from": self.dateTimeEdit_5.dateTime().toString('yyyy-MM-dd'),  # 出院时间开始
            "discharge_date_to": self.dateTimeEdit_3.dateTime().toString('yyyy-MM-dd'),  # 出院时间结束
            "unit_name": self.lineEdit_20.text(),
            "days_from": self.lineEdit_19.text(),
            "days_to": self.lineEdit_21.text(),
            "surgery_name": self.lineEdit_23.text(),
            "surgery_date_from": self.dateEdit.date().toString('yyyy-MM-dd'),
            "surgery_date_to": self.dateEdit_2.date().toString('yyyy-MM-dd'),
            "surgeon_name": self.lineEdit_22.text(),

        }


        search_info = {k: v for k, v in search_info.items() if len(v) > 0}

        records = search_surgery_info(**search_info)

        # 清空现有表格内容
        self.tableWidget.setRowCount(0)

        # 将查询结果插入到表格中
        for row_number, record in enumerate(records):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(record):
                self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))


if __name__ == '__main__':
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app = QApplication(sys.argv)

    mainWindow = QMainWindow()

    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
